In [ ]:
import numpy as np
import copy

def Q_R_factorization(A):
    n,k=A.shape
    Q=copy.deepcopy(np.zeros((n,k)))
    R=copy.deepcopy(np.zeros((k,k)))
    for i in range(k):
        if i == 0:
            q=copy.deepcopy(A[:,i])
            R[0][0]=np.linalg.norm(q)
            q=q/np.linalg.norm(q)
            for j in range(n):
                Q[j][i]=copy.deepcopy(q[j])
        
        else:
            q=copy.deepcopy(A[:,i])
            for j in range(i):#[j][i]
                R[j][i]=copy.deepcopy(np.dot(Q[:,j],A[:,i]))
                q-=R[j][i]*Q[:,j]

            R[i][i]=np.linalg.norm(q)
            q=q/np.linalg.norm(q)
            for h in range(n):
                Q[h][i]=copy.deepcopy(q[h])

    return Q,R      




def get_matrix():
    rows=int(input("Enter number of rows:"))
    columns=int(input("Enter number of columns:"))
    mat=[]
    for i in range(rows):
        mat.append(list(float(j) for j in input().split()))

    np_mat=np.array(mat)
    
    Q,R = Q_R_factorization(np_mat)
    return Q,R

Q,R=get_matrix()
print('Q matrix: ')
print(Q)
print('R matrix is:')
print(R)


# for example

#A=[[1 -1 4]      
#   [1 4 -2]
#   [1 4 2]
#   [1 -1 0]]

#Q=[[0.5 -0.5 0.5]
#   [0.5 0.5 -0.5]
#   [0.5 0.5 0.5]
#   [0.5 -0.5 -0.5]]

#R=[[2 3 2]
#   [0 5 -2]
#   [0 0 4]]